### PR TITLE
Attach to selected application's replicas

### LINKED ISSUE #118: The microservice application's debugger is attached when clicking "Attach" button of Dapr application
**OS:** Win10
**Build Version:** 20210702.3

**Repro Steps:**

1. Open the `tye-demo` project in VS Code -> F1 -> Tasks: Run Task -> Select "tye-run".(`microservice application`)
2. Open the `tye-dapr-demo` project in a new window -> F1 -> Tasks: Run Task -> Select "tye-run".(`dapr application`)
3. Navigate to Tye view, there are 2 tye applications in it -> Click "Attach" button of **dapr** application.
   image
4. Check whether the dapr application's debugger is attached.

**Expect:**
The dapr application's debugger is attached.

**Actual:**
The microservice application's debugger is attached. 
image

### PR DESCRIPTION
**Pull request by philliphoff**
Fixes an issue were we were still attaching to the first application's replicas when the "debug all" command was invoked, rather than the *actually selected* application (in cases when more than one application was running).

Resolves #118.

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -163,16 +164,10 @@ export function activate(context: vscode.ExtensionContext): Promise<void> {
...
+					const application = node.application;
 
-					// NOTE: We arbitrarily only attach to processes associated with the first application.
-					//       This matches the tree view, which also shows only that first application.
-					//       Future work will refactor the tree view and debugging for multiple applications
-					//       once Tye has better discovery support.
-					const application = applications[0];
-
-					if (application?.projectServices) {
+					if (node.application?.projectServices) {
```
Comment (pratiksanglikar) [inline src/extension.ts:170]: Nit: We can probably get away without the change on this line because `application` still has the value `node.application` assigned on line 168.

File: src/views/services/tyeApplicationNode.ts [hunk 2]
```diff
@@ -10,7 +10,7 @@ import TyeServiceNode from './tyeServiceNode';
 import { TyeClientProvider } from '../../services/tyeClient';
 import ext from '../../ext';
 
-export class TyeApplicationNode implements TreeNode {
+export default class TyeApplicationNode implements TreeNode {
```
Comment (pratiksanglikar) [inline src/views/services/tyeApplicationNode.ts:13]: Just curious, what is the reasoning behind making this a default export?

**Review by pratiksanglikar — APPROVED** [review]
Looks good!
Just a minor comment.

File: src/views/services/tyeApplicationNode.ts (hunk 2 above)
Comment (philliphoff) [reply src/views/services/tyeApplicationNode.ts:13]: Mostly to match how the other tree nodes were exported.  (I usually try to make the "main" thing in a file the default export (e.g. the implementation), with other related things (e.g. related interfaces) as explicit exports.

File: src/extension.ts (hunk 1 above)
Comment (philliphoff) [reply src/extension.ts]: Yes, I originally was going to eliminate the local `application`, but then changed my mind and forgot to revert that.

**Review by pratiksanglikar — APPROVED** [review]
